ElDorado.Gui/ViewModels/AccountsPayableViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ElDorado.Gui.ViewModels
{
    [NotMapped]
    public class AccountsPayableViewModel
    {
        public IEnumerable<PersonLedgerViewModel> AuthorLedgers { get; set; } = Enumerable.Empty<PersonLedgerViewModel>();

        public IEnumerable<PersonLedgerViewModel> EditorLedgers { get; set; } = Enumerable.Empty<PersonLedgerViewModel>();
        
        public decimal AuthorTotal => AuthorLedgers.Sum(al => al.Total);

        public decimal EditorTotal => EditorLedgers.Sum(el => el.Total);

        public decimal GrandTotal => AuthorTotal + EditorTotal;
    }
}

ElDorado.Gui/ViewModels/AccountsReceivableViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ElDorado.Gui.ViewModels
{
    [NotMapped]
    public class AccountsReceivableViewModel
    {
        public IEnumerable<AuthorLedgerViewModel> AuthorLedgers { get; set; } = Enumerable.Empty<AuthorLedgerViewModel>();
        public decimal Total => AuthorLedgers.Sum(al => al.Total);
    }
}

ElDorado.Gui/ViewModels/PostHustlingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElDorado.Gui.ViewModels
{
    public class PostHustlingViewModel
    {
        public IEnumerable<PostAuthorPairing> UnclaimedPosts { get; private set; } = Enumerable.Empty<PostAuthorPairing>();

        public PostHustlingViewModel(IEnumerable<PostAuthorPairing> blogPosts)
        {
            UnclaimedPosts = blogPosts;
        }

    }
}

ElDorado.Gui/Controllers/BlogPostsController.cs
using ElDorado.Console.Trello;
using ElDorado.Console.Wordpress;
using ElDorado.Domain;
using ElDorado.Gui.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace ElDorado.Gui.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly BlogContext _blogContext;
        private readonly WritingCalendarService _writingCalendarService;
        private readonly WordpressService _wordpressService;

        public string MapPath { get; set; }

        public BlogPostsController(BlogContext blogContext, WritingCalendarService writingCalendarService, WordpressService wordpressService)
        {
            _wordpressService = wordpressService;
            _writingCalendarService = writingCalendarService;
            _blogContext = blogContext;
        }

        public ActionResult Index(int blogId = 0, int authorId = 0, DateTime? draftDate = null, bool includeAll = false)
        {
            var postsFromEvaluatedDatabaseQuery = _blogContext.BlogPosts.ToList(); //I like the readability from these filtering methods we're using, and the cost tradeoff here just doesn't matter

            var filteredPosts = postsFromEvaluatedDatabaseQuery.Where(bp => bp.BlogId.DefaultMatches(blogId) && bp.AuthorId.DefaultMatches(authorId) && bp.DraftDate.DefaultMatches(draftDate));
            var currentPosts = filteredPosts.Where(bp => includeAll || (!bp.IsHitSubscribeFinished && bp.IsApproved));
            var orderedPosts = currentPosts.OrderBy(p => p.DraftDate);

            return View(new BlogPostIndexViewModel(orderedPosts, _blogContext));
        }

        public ActionResult Create(int blogId = 0)
        {
            return View(new BlogPostEditViewModel(new BlogPost() { BlogId = blogId }, _blogContext));
        }

        [HttpPost]
        public ActionResult Create(BlogPost post, string createNew = null)
        {
            #region Move to a service
            _blogContext.BlogPosts.Add(post);
            _blogContext.SaveChanges();
            _blogContext.UpdateBlogPostDependencies(post);

            InitializeTrelloService();
            _writingCalendarService.AddCard(post);

            post.CalculateAuthorPay();

            SyncToWordpress(post);

            _blogContext.SaveChanges();
            #endregion

            if (ModelState.IsValid)
                return RedirectToAppropriatePage(post, createNew);
            else
                return Create(post.BlogId);
        }

        public ActionResult Edit(int postId)
        {
            return View(GetViewModelForId(postId));
        }


        [HttpPost]
        public ActionResult Edit(BlogPostEditViewModel blogPostViewModel)
        {
            #region Move to a service
            _blogContext.BlogPosts.Attach(blogPostViewModel.Post);
            _blogContext.SetModified(blogPostViewModel.Post);
            _blogContext.UpdateBlogPostDependencies(blogPostViewModel.Post);
            blogPostViewModel.SetPay();

            if(blogPostViewModel.Post.WordpressId != 0)
               SyncToWordpress(blogPostViewModel.Post);

            InitializeTrelloService();
            _writingCalendarService.EditCard(blogPostViewModel.Post);

            _blogContext.SaveChanges();
            #endregion

            if (ModelState.IsValid)
                return RedirectToAction("Edit", new { postId = blogPostViewModel.Post.Id });
            else
                return Edit(blogPostViewModel.Post.Id);
        }

        public ActionResult Delete(int postId)
        {
            #region Move to a Service
            var post = _blogContext.BlogPosts.First(p => p.Id == postId);
            string trelloId = post.TrelloId;

            _blogContext.BlogPosts.Remove(post);
            _blogContext.SaveChanges();

            InitializeTrelloService();
            _writingCalendarService.DeleteCard(trelloId);

            AuthorizeWordpress();
            _wordpressService.DeleteFromWordpress(post);
            #endregion

            return RedirectToAction("Index");
        }

        public ActionResult Review(int postId)
        {
            var post = _blogContext.BlogPosts.First(p => p.Id == postId);

            AuthorizeWordpress();
            post.Content = _wordpressService.GetBlogPostById(post.WordpressId).Content;

            var viewModel = new PostReviewViewModel(post, new RenderedPostContents(post.Content));

            _blogContext.SaveChanges();
            return View(viewModel);
        }

        private ActionResult RedirectToAppropriatePage(BlogPost post, string createNew)
        {
            if (createNew == "Create and Add Another")
                return RedirectToAction("Create", new { blogId = post.BlogId });

            return RedirectToAction("Edit", new { postId = post.Id });
        }

        private void SyncToWordpress(BlogPost post)
        {
            try
            {
                AuthorizeWordpress();
                _wordpressService.SyncToWordpress(post);
            }
            catch(MissingAuthorException)
            {
                ModelState.AddModelError("Post.AuthorId", "Author not in Wordpress.");
            }
        }

        private BlogPostEditViewModel GetViewModelForId(int id)
        {
            var blogPost = _blogContext.BlogPosts.First(bp => bp.Id == id);
            return new BlogPostEditViewModel(blogPost, _blogContext);
        }

        private void InitializeTrelloService()
        {
            _writingCalendarService.Initialize(MapPath ?? Server.MapPath(@"~/App_Data/trello.cred"));
        }

        private void AuthorizeWordpress() => _wordpressService.AuthorizeUser(MapPath ?? Server.MapPath(@"~/App_Data/wordpress.cred"));
    }
}

ElDorado.Gui/Controllers/ReportsController.cs
using ElDorado.Domain;
using ElDorado.Gui.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElDorado.Gui.Controllers
{
    public class ReportsController : Controller
    {
        private readonly BlogContext _context;
        public DateTime Today { get; set; } = DateTime.Now;

        public ReportsController(BlogContext context)
        {
            _context = context;
        }

        public ActionResult PostHustling()
        {
            var allBlogPosts = _context.BlogPosts.ToList();
            var allAuthors = _context.Authors.ToList();
            var matchingPosts = allBlogPosts.Where(p => ShouldPostAppearInPostHustlingReport(p));

            var pairingsByDate = matchingPosts.Select(mp => new PostAuthorPairing(mp, allAuthors)).OrderBy(p => p.DraftDate);

            return View(new PostHustlingViewModel(pairingsByDate));
        }

        public ActionResult AuthorTimeliness()
        {
            var authors = _context.Authors.OrderBy(a => a.FirstName).ToList();
            return View(authors.Select(a => new AuthorTimelinessRecord(a)));
        }

        public ActionResult AccountsPayable(DateTime? userPickedDate = null)
        {
            var year = userPickedDate?.Year ?? 0;
            var month = userPickedDate?.Month ?? 0;

            var accountsPayableAuthorsForTheMonth = _context.Authors.ToList().Where(a => a.HasCompletedWorkInMonth(year, month)); //ToList here matters because without it, Linq tries to convert "HasCompletedWorkInMonth" to a SQL construct
            var accountsPayableEditorsForTheMonth = _context.Editors.ToList().Where(e => e.HasCompletedWorkInMonth(year, month));

            var viewModel = new AccountsPayableViewModel()
            {
                AuthorLedgers = accountsPayableAuthorsForTheMonth.Select(a => BuildAuthorLedger(a, year, month)).OrderBy(a => a.Name),
                EditorLedgers = accountsPayableEditorsForTheMonth.Select(e => BuildEditorLedger(e, year, month)).OrderBy(e => e.Name)
            };
            return View(viewModel);
        }

        public ActionResult HustlingEmail()
        {
            var posts = _context.BlogPosts.ToList();
            var matchingPosts = posts.Where(bp => ShouldPostAppearInHustlingEmail(bp)).ToList();

            return View(matchingPosts);
        }

        private static PersonLedgerViewModel BuildEditorLedger(Editor e, int year, int month)
        {
            return new PersonLedgerViewModel()
            {
                Name = $"{e.FirstName} {e.LastName}",
                LineItems = e.BlogPosts.Where(bp => bp.DraftCompleteDate.MatchesYearAndMonth(year, month)).Select(bp => new LedgerLineItemViewModel(bp) { Cost = bp.EditorPay })
            };
        }

        private static PersonLedgerViewModel BuildAuthorLedger(Author a, int year, int month)
        {
            return new PersonLedgerViewModel()
            {
                Name = $"{a.FirstName} {a.LastName}",
                LineItems = a.BlogPosts.Where(bp => bp.DraftCompleteDate.MatchesYearAndMonth(year, month)).Select(bp => new LedgerLineItemViewModel(bp) { Cost = bp.AuthorPay }).Concat(
                                    a.PostRefreshes.Where(pr => pr.SubmittedDate.MatchesYearAndMonth(year, month)).Select(pr => new LedgerLineItemViewModel(pr) { Cost = pr.AuthorPay }))
            };
        }

        private bool ShouldPostAppearInPostHustlingReport(BlogPost post)
        {
            return post.Author == null && post.DraftDate > Today && post.IsApproved;
        }

        private bool ShouldPostAppearInHustlingEmail(BlogPost post)
        {
            return post.Author == null && post.DraftCompleteDate == null && post.IsApproved &&
                (post.DraftDate == null || post.DraftDate >= Today);
        }
    }
}

ElDorado.Gui/Views/Reports/AccountsPayable.cshtml
@model ElDorado.Gui.ViewModels.AccountsPayableViewModel

@{
    ViewBag.Title = "Accounts Payable";
}

<h2>Accounts Payable</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('.monthpicker').datepicker({
            autoclose: true,
            dateFormat: 'mm/yyyy',
            onClose: function (dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        }); //Initialise any date pickers

    </script>
}

@using (Html.BeginForm("AccountsPayable", "Reports", FormMethod.Get))
{
    <input name="userPickedDate" id="userPickedDate" class="monthpicker"/>
    <input type="submit" value="Choose Month"/>
}
<h2>Authors</h2>
<table class="table">
    <tr>
        <th>Author</th>
        <th>Posts</th>
    </tr>
    @foreach (var ledger in Model.AuthorLedgers)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => ledger.Name)</td>
            <td>
                @foreach (var lineItem in ledger.LineItems)
                {
                    <table width="100%">
                        <tr>
                            <td>@Html.DisplayFor(modelItem => lineItem.Title)</td>
                            <td align="right">@Html.DisplayFor(modelItem => lineItem.Cost)</td>
                        </tr>
                    </table>
                }
            </td>
        </tr>
        <tr>
            <td></td>
            <td align="right"><b>@Html.DisplayFor(modelItem => ledger.Total)</b></td>
        </tr>
    }
    <tr>
        <td><b>Author Total</b></td>
        <td align="right"><b>@Html.DisplayFor(modelItem => Model.AuthorTotal)</b></td>
    </tr>
</table>

<h2>Editors</h2>
<table class="table">
    <tr>
        <th>Editor</th>
        <th>Posts</th>
    </tr>
    @foreach (var ledger in Model.EditorLedgers)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => ledger.Name)</td>
            <td>
                @foreach (var lineItem in ledger.LineItems)
                {
                    <table width="100%">
                        <tr>
                            <td>@Html.DisplayFor(modelItem => lineItem.Title)</td>
                            <td align="right">@Html.DisplayFor(modelItem => lineItem.Cost)</td>
                        </tr>
                    </table>
                }
            </td>
        </tr>
        <tr>
            <td></td>
            <td align="right"><b>@Html.DisplayFor(modelItem => ledger.Total)</b></td>
        </tr>
    }
    <tr>
        <td><b>Editor Total</b></td>
        <td align="right"><b>@Html.DisplayFor(modelItem => Model.EditorTotal)</b></td>
    </tr>
</table>

<table class="table">
    <tr>
        <td><h3><b>Grand Total:</b></h3></td>
        <td align="right"><h3><b>@Model.GrandTotal</b></h3></td>
    </tr>
</table>

ElDorado.Gui/Views/Reports/AccountsReceivable.cshtml
@model ElDorado.Gui.ViewModels.AccountsReceivableViewModel

@{
    ViewBag.Title = "AccountsReceivable";
}

<h2>AccountsReceivable</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('.monthpicker').datepicker({
            autoclose: true,
            dateFormat: 'mm/yyyy',
            onClose: function (dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        }); //Initialise any date pickers

    </script>
}

@using (Html.BeginForm("AccountsReceivable", "Reports", FormMethod.Get))
{
    <input name="userPickedDate" id="userPickedDate" class="monthpicker"/>
    <input type="submit" value="Choose Month"/>
}
<table class="table">
    <tr>
        <th>Author</th>
        <th>Posts</th>
    </tr>
    @foreach (var ledger in Model.AuthorLedgers)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => ledger.Name)</td>
            <td>
                @foreach (var post in ledger.Posts)
                {
                    <table width="100%">
                        <tr>
                            <td>@Html.DisplayFor(modelItem => post.Title)</td>
                            <td align="right">@Html.DisplayFor(modelItem => post.Cost)</td>
                        </tr>
                    </table>
                }
            </td>
        </tr>
        <tr>
            <td></td>
            <td align="right"><b>@Html.DisplayFor(modelItem => ledger.Total)</b></td>
        </tr>
    }
    <tr>
        <td>Grand Total</td>
        <td align="right"><b>@Html.DisplayFor(modelItem => Model.Total)</b></td>
    </tr>
</table>

ElDorado.Gui/Views/Reports/AuthorTimeliness.cshtml
@model IEnumerable<ElDorado.Gui.ViewModels.AuthorTimelinessRecord>

@{
    ViewBag.Title = "AuthorTimeliness";
}

<h2>AuthorTimelinessReport</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.PostCount)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Timeliness)</th>
        <th>@Html.DisplayNameFor(model => model.TotalPosts)</th>
        <th>@Html.DisplayNameFor(model => model.LatePosts)</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.PostCount)</td>
        <td>@Html.DisplayFor(modelItem => item.Name)</td>
        <td>@Html.DisplayFor(modelItem => item.Timeliness)</td>
        <td>@Html.DisplayFor(modelItem => item.TotalPosts)</td>
        <td>@Html.DisplayFor(modelItem => item.LatePosts)</td>
    </tr>
}

</table>

ElDorado.Gui/Views/Reports/HustlingEmail.cshtml
@model IEnumerable<ElDorado.Domain.BlogPost>

@{
    ViewBag.Title = "HustlingEmail";
}

<h2>Internal Hustling Email</h2>

&lt;table border="1" cellpadding="10" class="mc-table"&gt;
<br />
&lt;tr&gt;
&lt;th style="width:45%"&gt;Post Title (Click for More Info)&lt;/th&gt;&lt;th&gt;Client&lt;/th&gt;&lt;th&gt;Due&lt;/th&gt;&lt;th&gt;Click to Claim&lt;/th&gt;
<br />
@foreach (var item in Model)
{
    @Html.Raw("&lt;tr&gt;");

    @Html.Raw($"&lt;td&gt;&lt;a href=\"https://trello.com/c/{item.TrelloId}\"&gt;{item.Title}&lt;/a&gt;&lt;/td&gt;");
    @Html.Raw($"&lt;td&gt;{item.BlogCompanyName}&lt;/td&gt;");
    if (@item.DraftDate != null)
    {
        @Html.Raw($"&lt;td&gt;{item.DraftDate.Value.ToShortDateString()}&lt;/td&gt;");
    }
    else
    {
        @Html.Raw("&lt;td&gt;Flexible&lt;/td&gt;");
    }
    @Html.Raw($"&lt;td&gt;&lt;a href=\"mailto:iwantapost@hitsubscribe.com?subject={Uri.EscapeDataString(item.Title)}\">This my post!&lt;/a&gt;&lt;/td&gt;");

    @Html.Raw("&lt;/tr&gt;");
    <br />
}
&lt;/table&gt;

<h2>External Hustling Email</h2>

&lt;table border="1" cellpadding="10" class="mc-table"&gt;
<br />
&lt;tr&gt;
&lt;th style="width:45%"&gt;Post Title&lt;/th&gt;&lt;th&gt;Rate&lt;/th&gt;&lt;th&gt;Due&lt;/th&gt;&lt;th&gt;Click to Claim&lt;/th&gt;
<br />
@foreach (var item in Model)
{
    @Html.Raw("&lt;tr&gt;");

    @Html.Raw($"&lt;td&gt;{item.Title}&lt;/td&gt;");
    @Html.Raw($"&lt;td&gt;${(item.IsDoublePost ? "200" : "100")} &lt;/td&gt;");
    if (@item.DraftDate != null)
    {
        @Html.Raw($"&lt;td&gt;{item.DraftDate.Value.ToShortDateString()}&lt;/td&gt;");
    }
    else
    {
        @Html.Raw("&lt;td&gt;Flexible&lt;/td&gt;");
    }
    @Html.Raw($"&lt;td&gt;&lt;a href=\"mailto:iwantapost@hitsubscribe.com?subject=I'm Interested in {item.Title}\">This my post!&lt;/a&gt;&lt;/td&gt;");

    @Html.Raw("&lt;/tr&gt;");
    <br />
}
&lt;/table&gt;

ElDorado.Gui/Views/Reports/PostHustling.cshtml
@model ElDorado.Gui.ViewModels.PostHustlingViewModel

@{
    ViewBag.Title = "PostHustling";
}

<h2>Post Hustling Report</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.UnclaimedPosts.First().CompanyName)</th>
        <th>@Html.DisplayNameFor(model => model.UnclaimedPosts.First().Title)</th>
        <th>@Html.DisplayNameFor(model => model.UnclaimedPosts.First().DraftDate)</th>
        <th>@Html.DisplayNameFor(model => model.UnclaimedPosts.First().IsApproved)</th>
        <th>@Html.DisplayNameFor(model => model.UnclaimedPosts.First().IsDoublePost)</th>
        <th>Available Authors</th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model.UnclaimedPosts) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.CompanyName)</td>
        <td>@Html.DisplayFor(modelItem => item.Title)</td>
        <td>@Html.DisplayFor(modelItem => item.DraftDate)</td>
        <td>@Html.DisplayFor(modelItem => item.IsApproved)</td>
        <td>@Html.DisplayFor(modelItem => item.IsDoublePost)</td>
        <td>@Html.DisplayFor(modelItem => item.Authors)</td>
        <td>
            @Html.ActionLink("Edit", "Edit", "BlogPosts", new { postId = item.Id }, null)
        </td>
    </tr>
}

</table>